# Generated by Django 2.1.2 on 2018-10-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='uploads/')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Info')),
            ],
        ),
        migrations.RemoveField(
            model_name='point',
            name='picture',
        ),
        migrations.AddField(
            model_name='point',
            name='latitude',
            field=models.FloatField(default=1.0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='longitude',
            field=models.FloatField(default=1.0, max_length=25),
            preserve_default=False,
        ),
    ]
